//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuffmanPlayground.Mobile.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuffmanPlayground.Mobile.Client.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit:.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to decode page.
        /// </summary>
        public static string CopytoDecodePageButton {
            get {
                return ResourceManager.GetString("CopytoDecodePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to decode page.
        /// </summary>
        public static string CopytoDecodePageButtonSemanticHint {
            get {
                return ResourceManager.GetString("CopytoDecodePageButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string DecodeButton {
            get {
                return ResourceManager.GetString("DecodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string DecodeButtonSemanticHint {
            get {
                return ResourceManager.GetString("DecodeButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Decode Page.
        /// </summary>
        public static string DecodeImageButtonSemanticHint {
            get {
                return ResourceManager.GetString("DecodeImageButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching table (JSON).
        /// </summary>
        public static string DecodeMatchingTableJsonPlaceHolder {
            get {
                return ResourceManager.GetString("DecodeMatchingTableJsonPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Text.
        /// </summary>
        public static string DecodePageTitle {
            get {
                return ResourceManager.GetString("DecodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string DecodeResultEditorPlaceHolder {
            get {
                return ResourceManager.GetString("DecodeResultEditorPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to decode.
        /// </summary>
        public static string DecodeTextEditorPlaceHoler {
            get {
                return ResourceManager.GetString("DecodeTextEditorPlaceHoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string EncodeButton {
            get {
                return ResourceManager.GetString("EncodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string EncodeButtonSemanticHint {
            get {
                return ResourceManager.GetString("EncodeButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits.
        /// </summary>
        public static string EncodedSizeAfterLabel {
            get {
                return ResourceManager.GetString("EncodedSizeAfterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded:.
        /// </summary>
        public static string EncodedSizeBeforeLabel {
            get {
                return ResourceManager.GetString("EncodedSizeBeforeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tex to decode.
        /// </summary>
        public static string EncodeEditorPlaceHoler {
            get {
                return ResourceManager.GetString("EncodeEditorPlaceHoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Encode Page.
        /// </summary>
        public static string EncodeImageButtonSemanticHint {
            get {
                return ResourceManager.GetString("EncodeImageButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching table.
        /// </summary>
        public static string EncodeMatchingTablePageTitle {
            get {
                return ResourceManager.GetString("EncodeMatchingTablePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode text.
        /// </summary>
        public static string EncodePageTitle {
            get {
                return ResourceManager.GetString("EncodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary tree.
        /// </summary>
        public static string EncodeTreePageTitle {
            get {
                return ResourceManager.GetString("EncodeTreePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string MatchingTableButton {
            get {
                return ResourceManager.GetString("MatchingTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string MatchingTableButtonSemanticHint {
            get {
                return ResourceManager.GetString("MatchingTableButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits.
        /// </summary>
        public static string OriginalSizeAfterLabel {
            get {
                return ResourceManager.GetString("OriginalSizeAfterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin:.
        /// </summary>
        public static string OriginalSizeBeforeLabel {
            get {
                return ResourceManager.GetString("OriginalSizeBeforeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string TreeButton {
            get {
                return ResourceManager.GetString("TreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string TreeButtonSemanticHint {
            get {
                return ResourceManager.GetString("TreeButtonSemanticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Color.
        /// </summary>
        public static string TreeLineColorSettingLabel {
            get {
                return ResourceManager.GetString("TreeLineColorSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Label Color.
        /// </summary>
        public static string TreeLineLabelColorSettingLabel {
            get {
                return ResourceManager.GetString("TreeLineLabelColorSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Color.
        /// </summary>
        public static string TreeNodeColorSettingLabel {
            get {
                return ResourceManager.GetString("TreeNodeColorSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify node height.
        /// </summary>
        public static string TreeNodeHeightSemanticHintSettingLabel1 {
            get {
                return ResourceManager.GetString("TreeNodeHeightSemanticHintSettingLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node height.
        /// </summary>
        public static string TreeNodeHeightSettingLabel {
            get {
                return ResourceManager.GetString("TreeNodeHeightSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Label Color.
        /// </summary>
        public static string TreeNodeLabelColorSettingLabel {
            get {
                return ResourceManager.GetString("TreeNodeLabelColorSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify node width.
        /// </summary>
        public static string TreeNodeWidthSemanticHintSettingLabel {
            get {
                return ResourceManager.GetString("TreeNodeWidthSemanticHintSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node width.
        /// </summary>
        public static string TreeNodeWidthSettingLabel {
            get {
                return ResourceManager.GetString("TreeNodeWidthSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TreeSettingsLabel {
            get {
                return ResourceManager.GetString("TreeSettingsLabel", resourceCulture);
            }
        }
    }
}
