name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: 🔍 Build & Analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x-preview'

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache .NET tools
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-tools-

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-coverage

      - name: 🔍 Set SonarCloud Analysis Parameters
        id: sonar-params
        env:
          PR_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.head_ref }}
          PR_BASE: ${{ github.base_ref }}
          BRANCH_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
        shell: bash
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            args="/d:sonar.github.repository=${PR_REPO}"
            args="$args /d:sonar.pullrequest.key=${PR_NUMBER}"
            args="$args /d:sonar.pullrequest.branch=${PR_BRANCH}"
            args="$args /d:sonar.pullrequest.base=${PR_BASE}"
            echo "sonar_args=$args" >> $GITHUB_OUTPUT
          else
            echo "sonar_args=/d:sonar.branch.name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: 🔍 SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          SONAR_ORG: ${{ github.repository_owner }}
          SONAR_ARGS: ${{ steps.sonar-params.outputs.sonar_args }}
        run: |
          dotnet sonarscanner begin \
            /k:"${SONAR_PROJECT_KEY}" \
            /o:"${SONAR_ORG}" \
            /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
            /d:sonar.coverage.exclusions="**/Program.cs" \
            /d:sonar.scm.provider=git \
            /d:sonar.qualitygate.wait=true \
            ${SONAR_ARGS}

      - name: 🏗️ Build & Test
        run: |
          dotnet build ./src/HuffmanWeb/HuffmanWeb.Server/HuffmanWeb.Server.csproj --no-incremental
          dotnet-coverage collect 'dotnet test ./src/HuffmanWeb/HuffmanWeb.Server/HuffmanWeb.Server.csproj' -f xml -o 'coverage.xml'
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  build-docker:
    name: 🛠️ Build & Push Docker
    needs: analyze
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: 🔑 Docker Login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build & Push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v6
        with:
          context: .
          file: ./src/HuffmanWeb/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/huffmanweb:latest

  deploy:
    name: 🚀 Deploy
    needs: build-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🌐 Deploy to VPS
        uses: appleboy/ssh-action@7d3c46ff3fa0244d173c2174fe6d106ddfb4a729 # v1.0.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo docker container stop huffmanweb || true
            sudo docker container rm huffmanweb || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/huffmanweb:latest
            sudo docker run -d --name huffmanweb -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/huffmanweb:latest

